name: Build, Scan & Publish

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read        # potrzebne do checkout
      packages: write       # potrzebne do pushu do GHCR

    steps:
    # --- kod ----------------------------------------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # --- buildx -------------------------------------------------------
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        buildkitd-flags: --allow-insecure-entitlement network.host

    # --- loginy -------------------------------------------------------
    - name: Log in to Docker Hub (cache)
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    # --- budowanie ----------------------------------------------------
    - name: Build and push multi-arch image (cache + GHCR)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: |
          type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pogodynka-cache:buildcache
          type=inline
        cache-to: |
          type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pogodynka-cache:buildcache,mode=max
          type=inline
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
          ghcr.io/${{ github.repository }}:latest

    # --- skan CVE -----------------------------------------------------
    - name: Scan image (Trivy)
      uses: aquasecurity/trivy-action@0.30.0   # <-- bez „v”, najnowsza wersja
      with:
        image-ref: ghcr.io/${{ github.repository }}:${{ github.sha }}
        severity: CRITICAL,HIGH
        exit-code: 1          # przerwij workflow, jeśli znajdzie HIGH/CRITICAL
        ignore-unfixed: true  # (opcjonalnie) pomija CVE bez łatki
        format: table
        vuln-type: os,library
        timeout: 10m

    # --- sukces -------------------------------------------------------
    - name: Verify and finish
      run: echo "✅ Image built, scanned (no CRITICAL/HIGH) and pushed"
