# .github/workflows/build-and-scan.yml
name: Build, Scan & Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. QEMU for multi-arch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      # 4. Login to Docker Hub (cache)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Login to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: pawlox62
          password: ${{ secrets.GHCR_TOKEN }}

      # 6. Build & push multi-arch image (cache + GHCR)
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pogodynka-cache:buildcache
            type=inline
          cache-to: |
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pogodynka-cache:buildcache,mode=max
            type=inline
          tags: |
            ghcr.io/pawlox62/pogodynka:${{ github.sha }}
            ghcr.io/pawlox62/pogodynka:latest

      # 7. CVE scan with Trivy Action
      - name: Scan image for HIGH/CRITICAL CVEs
        uses: aquasecurity/trivy-action@v0.2.0
        with:
          image-ref: ghcr.io/pawlox62/pogodynka:${{ github.sha }}
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
          vuln-type: os,library

      # 8. Success message
      - name: Done
        if: success()
        run: echo "✅ Image built, scanned (no CRITICAL/HIGH) and pushed to GHCR"
