# .github/workflows/build-and-scan.yml
name: Build, Scan & Publish

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    # ✅ jedno miejsce, w którym definiujemy poprawną ścieżkę obrazu
    env:
      IMAGE: ghcr.io/${{ toLower(github.repository) }}

    permissions:
      contents: read
      packages: write

    steps:
    # --- kod -----------------------------------------------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # --- buildx / qemu -------------------------------------------------------
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        buildkitd-flags: --allow-insecure-entitlement network.host

    # --- loginy --------------------------------------------------------------
    - name: Log in to Docker Hub (cache)
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    # --- build & push --------------------------------------------------------
    - name: Build and push multi-arch image (cache + GHCR)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: |
          type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pogodynka-cache:buildcache
          type=inline
        cache-to: |
          type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pogodynka-cache:buildcache,mode=max
          type=inline
        tags: |
          ${{ env.IMAGE }}:${{ github.sha }}
          ${{ env.IMAGE }}:latest

    # --- skan CVE ------------------------------------------------------------
    - name: Scan image (Trivy)
      uses: aquasecurity/trivy-action@0.30.0   # bez „v” w nazwie
      with:
        image-ref: ${{ env.IMAGE }}:${{ github.sha }}
        severity: CRITICAL,HIGH
        exit-code: 1
        ignore-unfixed: true
        format: table
        vuln-type: os,library
        timeout: 10m

    # --- sukces --------------------------------------------------------------
    - name: Verify and finish
      run: echo "✅ Image built, scanned (no CRITICAL/HIGH) and pushed"
